= Relaton CLI (relaton-cli): Relaton Command-line Interface

image:https://img.shields.io/gem/v/relaton-cli.svg["Gem Version", link="https://rubygems.org/gems/relaton-cli"]
image:https://img.shields.io/travis/riboseinc/relaton-cli/master.svg["Build Status", link="https://travis-ci.org/riboseinc/relaton-cli"]
image:https://codeclimate.com/github/riboseinc/relaton-cli/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/riboseinc/relaton-cli"]

Documentation in development.

Please refer to https://github.com/riboseinc/relaton.

== Executables

The following executables are included:

=== relaton-concatenate

```
relaton-concatenate DIRECTORY
```

Iterates through all the Relaton YAML files in DIRECTORY, and converts them in-place into Relaton XML.

Iterates through all the Relaton XML files in DIRECTORY (including those just converted from Relaton YAML),
and outputs to stdout a `relaton-collection` document containing all the Relaton XML objects read in.

=== relaton-fetch

```
relaton-fetch -t TYPE -y YEAR code
```

Fetch the Relaton XML entry corresponding to the document identifier `code`. 

* `YEAR` is optional, and specifies the year of publication of the standard.
* `TYPE` specifies the standards class library to be used, that the identifier is part of; the recognised 
values for `TYPE` are `isobib`, `ietfbib`, `iecbib`, `gbbib`.

=== relaton-metanorma-extract

```
relaton-metanorma-extract Metanorma-XML-Directory Relaton-XML-Directory
```

Iterate through all the Metanorma XML files in `Metanorma-XML-Directory`, and extract the `bibdata`
element from each. Save the `bibdata` element for each file to `Relaton-XML-Directory`, as the Relaton XML
description for that file. If a document identifier is present in `bibdata`, it is used as the name of the
file; otherwise, the original file name is used.

=== relaton-xml-html

```
relaton-xml-html <relaton-xml> <stylesheet> <output-root> <html-template>
```

Render a Relaton Collection XML as an HTML file. Used to generate an HTML index of standards.

* `relaton-xml` is the Relaton Collection XML file.
* `stylesheet` is the CSS stylesheet to be used to style the output. For the CSS styling of each bibliographic element, see below.
* `output-root` is the directory containing the Relaton XML for each file, named after the document identifier (as generated by `relaton-metanorma-extract`)
* `html-template` is the HTML Liquid Template file into which the bibliographic entries are to be inserted.  The HTML Template recognises the following parameters:
** `css`: where the CSS stylesheet `stylesheet` is injected
** `title`: the Title of the collection, `./relaton-collection/title` in `relaton-xml`
** `author`: the Author of the collection, `./relaton-collection/contributor[role/@type = 'author']/organization/name` in `relaton-xml`
** `content`: the list of resources generated by the script

Sample HTML output for a bibliographic entry:

```xml
  <div class="document">
    <div class="doc-line">
      <div class="doc-identifier">
        <h2>
          <a href="http://calconnect.org/pubdocs/CD0507%20CalDAV%20Use%20Cases%20V1.0.html">CC/R 3101</a>
        </h2>
      </div>
      <div class="doc-type-wrap">
        <div class="doc-type report">report</div>
      </div>
    </div>
    <div class="doc-title">
      <h3>
        <a href="http://calconnect.org/pubdocs/CD0507%20CalDAV%20Use%20Cases%20V1.0.html">CalConnect XLIII -- Position on the European Union daylight-savings timezone change</a>
      </h3>
    </div>
    <div class="doc-info cancelled">
      <div class="doc-stage cancelled">cancelled</div>
      <div class="doc-dates">
        <div class="doc-updated">2019-10-17</div>
      </div>
    </div>
    <div class="doc-bib">
      <div class="doc-bib-relaton">
        <a href="csd/cc-r-3101.xml">Relaton XML</a>
      </div>
    </div>
    <div class="doc-access">
      <div class="doc-access-button-html">
        <a href="http://calconnect.org/pubdocs/CD0507%20CalDAV%20Use%20Cases%20V1.0.html">HTML</a>
      </div>
      <div class="doc-access-button-pdf">
        <a href="http://calconnect.org/pubdocs/CD0507%20CalDAV%20Use%20Cases%20V1.0.pdf">PDF</a>
      </div>
      <div class="doc-access-button-doc">
        <a href="http://calconnect.org/pubdocs/CD0507%20CalDAV%20Use%20Cases%20V1.0.doc">Word</a>
      </div>
      <div class="doc-access-button-xml">
        <a href="http://calconnect.org/pubdocs/CD0507%20CalDAV%20Use%20Cases%20V1.0.xml">XML</a>
      </div>
    </div>
  </div>
```

=== relaton-yaml-xml

```
relaton-yaml-xml -R relaton-dir yaml-file
```

Convert a Relaton YAML file into a Relaton Collection XML.

The Relaton YAML file contains some initial metadata, and a list of metadata about each bibliographic entry. The following is a sample:

```yaml
htmlstylesheet: ./index-style.css
root:
  title: CalConnect Standards Registry
  author: "CalConnect: The Calendaring and Scheduling Consortium"
  items:
    - technical_committee: TC VCARD
      docid: CC 18001
      doctype: standard
      title: "Date and time -- Representations for information interchange -- Part 1: Basic rules"
      stage: Published
      revdate: 2018-10-17
      xml: standards/csd-datetime-explict/csd-datetime-explict.xml
      html: standards/csd-datetime-explict/csd-datetime-explict.html
      pdf: standards/csd-datetime-explict/csd-datetime-explict.pdf
      doc: standards/csd-datetime-explict/csd-datetime-explict.doc
      relaton: standards/csd-datetime-explict/cc-18001.xml
    - technical_committee: TC PUBLISH
      docid: CC/DIR 10001
      doctype: governance
      title: "Standardization and publication"
      stage: proposal
      revdate: 2018-10-17
      uri: standards/csd-standardization/csd-standardization.xml
```

