require_relative "relaton/bibcollection"
require_relative "relaton/bibcollectionnew"
require_relative "relaton/bibdata"
require_relative "relaton/element_finder"
require_relative "relaton/xml_document"
