#!/usr/bin/env ruby

# Invoke as: ./relaton-doc FILENAME STYLESHEET RELATON-ROOT
require "nokogiri"
require "relaton/cli"

unless ARGV.size == 3
  warn "Invoke as: ./relaton-doc <relaton-xml> <stylesheet> <output-root>"
  exit
end

filename = ARGV[0]
stylesheet = ARGV[1]
relaton_root = ARGV[2] || "relaton"

file = File.read(ARGV[0], encoding: "utf-8")

xml_to_html = Relaton::Cli::XmlToHtmlRenderer.new

File.open(filename.sub(/\.xml$/, ".html"), "w:UTF-8") do |f|
  f.write(xml_to_html.render(file, stylesheet, relaton_root))
end

