#!/usr/bin/env ruby

# Invoke as: ./relaton-doc FILENAME STYLESHEET RELATON-ROOT
require "yaml"
require "optparse"
require "fileutils"
require "relaton/cli"


if ARGV.size < 2 || ARGV.size > 3
  warn "Invoke as: ./relaton-xml-html <relaton-index-xml> <stylesheet> <liquid-template-dir>"
  exit
end

filename = ARGV[0]
file = File.read(filename, encoding: "utf-8")

puts ARGV.inspect

xml_to_html = Relaton::Cli::XmlToHtmlRenderer.new({
  stylesheet: ARGV[1],
  liquid_dir: ARGV[2]
})

File.open(filename.sub(/\.xml$/, ".html"), "w:UTF-8") do |f|
  f.write(xml_to_html.render(file))
end

